require('wrapping').soft_wrap_mode()

vim.api.nvim_set_keymap("n", "j", 'gj', { noremap = true })
vim.api.nvim_set_keymap("n", "k", 'gk', { noremap = true })
vim.api.nvim_set_keymap("n", "^", 'g^', { noremap = true })
vim.api.nvim_set_keymap("n", "$", 'g$', { noremap = true })
vim.api.nvim_set_keymap("n", "gj", 'j', { noremap = true })
vim.api.nvim_set_keymap("n", "gk", 'k', { noremap = true })
vim.api.nvim_set_keymap("n", "g^", '^', { noremap = true })
vim.api.nvim_set_keymap("n", "g$", '$', { noremap = true })
